In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
data = pd.read_excel(r'C:\Users\HP\Downloads\Data Sceince_tutorial\iris.xlsx')

In [7]:
data.head()

SL   SW   PL   PW Classification
0  5.1  3.5  1.4  0.2    Iris-setosa
1  4.9  3.0  1.4  0.2    Iris-setosa
2  4.7  3.2  1.3  0.2    Iris-setosa
3  4.6  3.1  1.5  0.2    Iris-setosa
4  5.0  3.6  1.4  0.2    Iris-setosa

In [9]:
data.columns

Index(['SL', 'SW', 'PL', 'PW', 'Classification'], dtype='object')

In [11]:
data.isnull().sum()

SL                0
SW                0
PL                0
PW                0
Classification    0
dtype: int64

In [13]:
data.shape

(150, 5)

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   SL              150 non-null    float64
 1   SW              150 non-null    float64
 2   PL              150 non-null    float64
 3   PW              150 non-null    float64
 4   Classification  150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [19]:
data['Classification'].nunique()

3

In [21]:
data['Classification'].value_counts()

Classification
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [23]:
from sklearn.preprocessing import LabelEncoder

In [29]:
label_encoder = LabelEncoder()
data['Classification'] = label_encoder.fit_transform(data['Classification'])
data.head()

SL   SW   PL   PW  Classification
0  5.1  3.5  1.4  0.2               0
1  4.9  3.0  1.4  0.2               0
2  4.7  3.2  1.3  0.2               0
3  4.6  3.1  1.5  0.2               0
4  5.0  3.6  1.4  0.2               0

In [42]:
x = data.drop(['Classification'],axis =1)
y = data['Classification']

In [45]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25,random_state = 42)

## Logistic Regression

In [47]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg = log_reg.fit(x_train,y_train)

In [49]:
y_pred = log_reg.predict(x_test)

In [51]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0])

In [53]:
from sklearn.metrics import confusion_matrix,accuracy_score, precision_score,recall_score, f1_score

In [55]:
print("Accuracy is ", accuracy_score(y_test,y_pred))

Accuracy is  1.0


In [57]:
print("Confusion matrix ", confusion_matrix(y_test,y_pred))

Confusion matrix  [[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]


## KNN

In [60]:
from sklearn.neighbors import KNeighborsClassifier

In [62]:
knn = KNeighborsClassifier(n_neighbors = 5, metric = 'euclidean')
knn.fit(x_train,y_train)

KNeighborsClassifier(metric='euclidean')

In [64]:
y_predictions = knn.predict(x_test)

In [66]:
print("Confusion matrix ", confusion_matrix(y_test,y_predictions))

Confusion matrix  [[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]


In [68]:
print('Accuracy is :',accuracy_score(y_test,y_predictions))

Accuracy is : 1.0


In [70]:
x_new = np.array([[5,5.1,3,3.5]])
prediction = knn.predict(x_new)
prediction

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([1])

## Naive Bayes

In [81]:
from sklearn.naive_bayes import GaussianNB

In [83]:
nb_classifier = GaussianNB()
nb_classifier.fit(x_train,y_train)

GaussianNB()

In [85]:
y_pred = nb_classifier.predict(x_test)

In [91]:
print('Accuracy is :',accuracy_score(y_test,y_pred))
print('Precision is :',precision_score(y_pred,y_test,average='micro'))


Accuracy is : 1.0
Precision is : 1.0


In [93]:
print("Confusion matrix ", confusion_matrix(y_test,y_pred))

Confusion matrix  [[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]


## SVM

In [97]:
from sklearn.svm import SVC

In [99]:
svm_cls = SVC(kernel = 'linear')
svm_cls = svm_cls.fit(x_train,y_train)
y_pred_svm = svm_cls.predict(x_test)

In [101]:
confusion_matrix(y_test,y_pred_svm)

array([[15,  0,  0],
       [ 0, 11,  0],
       [ 0,  0, 12]], dtype=int64)

In [103]:
accuracy_score(y_test,y_pred_svm)

1.0

In [105]:
precision_score(y_test,y_pred_svm, average = 'micro')

1.0

## Decision Tree

In [108]:
from sklearn.tree import DecisionTreeClassifier

In [110]:
dt_cls = DecisionTreeClassifier()
dt_cls = dt_cls.fit(x_train,y_train)

In [112]:
y_pred_dt = dt_cls.predict(x_test)

In [114]:
confusion_matrix(y_test,y_pred_dt)

array([[15,  0,  0],
       [ 0, 11,  0],
       [ 0,  0, 12]], dtype=int64)

In [116]:
accuracy_score(y_test,y_pred_dt)

1.0

In [118]:
precision_score(y_test,y_pred_dt, average = 'micro')

1.0

## Random Forest

In [121]:
from sklearn.ensemble import RandomForestClassifier

In [123]:
rf_cls = DecisionTreeClassifier()
rf_cls = rf_cls.fit(x_train,y_train)

In [125]:
y_pred_rf = rf_cls.predict(x_test)

In [127]:
confusion_matrix(y_test,y_pred_rf)

array([[15,  0,  0],
       [ 0, 11,  0],
       [ 0,  0, 12]], dtype=int64)

In [129]:
accuracy_score(y_test,y_pred_rf)

1.0

In [131]:
precision_score(y_test,y_pred_rf, average = 'micro')

1.0

## All the classifications gives the result with accuracy 1